apiVersion: apps/v1
kind: Deployment
metadata:
  name: party-service
  namespace: aanspace
  labels:
    app: party-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: party-service
  template:
    metadata:
      labels:
        app: party-service
    spec:
      containers:
        - name: party-service
          image: gog1/party-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

